module.exports = {
  heroes: [
    {
      id: 1,
      aliases: ["am"],
      shortName: "antimage",
      displayName: "Anti-Mage",
      name: "npc_dota_hero_antimage",
    },
    {
      id: 2,
      aliases: [],
      shortName: "axe",
      displayName: "Axe",
      name: "npc_dota_hero_axe",
    },
    {
      id: 3,
      aliases: [],
      shortName: "bane",
      displayName: "Bane",
      name: "npc_dota_hero_bane",
    },
    {
      id: 4,
      aliases: ["bs"],
      shortName: "bloodseeker",
      displayName: "Bloodseeker",
      name: "npc_dota_hero_bloodseeker",
    },
    {
      id: 5,
      aliases: ["cm", "rylai"],
      shortName: "crystal_maiden",
      displayName: "Crystal Maiden",
      name: "npc_dota_hero_crystal_maiden",
    },
    {
      id: 6,
      aliases: [],
      shortName: "drow_ranger",
      displayName: "Drow Ranger",
      name: "npc_dota_hero_drow_ranger",
    },
    {
      id: 7,
      aliases: [],
      shortName: "earthshaker",
      displayName: "Earthshaker",
      name: "npc_dota_hero_earthshaker",
    },
    {
      id: 8,
      aliases: [],
      shortName: "juggernaut",
      displayName: "Juggernaut",
      name: "npc_dota_hero_juggernaut",
    },
    {
      id: 9,
      aliases: [],
      shortName: "mirana",
      displayName: "Mirana",
      name: "npc_dota_hero_mirana",
    },
    {
      id: 10,
      aliases: [],
      shortName: "morphling",
      displayName: "Morphling",
      name: "npc_dota_hero_morphling",
    },
    {
      id: 11,
      aliases: ["sf"],
      shortName: "nevermore",
      displayName: "Shadow Fiend",
      name: "npc_dota_hero_nevermore",
    },
    {
      id: 12,
      aliases: ["pl"],
      shortName: "phantom_lancer",
      displayName: "Phantom Lancer",
      name: "npc_dota_hero_phantom_lancer",
    },
    {
      id: 13,
      aliases: [],
      shortName: "puck",
      displayName: "Puck",
      name: "npc_dota_hero_puck",
    },
    {
      id: 14,
      aliases: [],
      shortName: "pudge",
      displayName: "Pudge",
      name: "npc_dota_hero_pudge",
    },
    {
      id: 15,
      aliases: [],
      shortName: "razor",
      displayName: "Razor",
      name: "npc_dota_hero_razor",
    },
    {
      id: 16,
      aliases: ["sk"],
      shortName: "sand_king",
      displayName: "Sand King",
      name: "npc_dota_hero_sand_king",
    },
    {
      id: 17,
      aliases: ["ss", "raijin"],
      shortName: "storm_spirit",
      displayName: "Storm Spirit",
      name: "npc_dota_hero_storm_spirit",
    },
    {
      id: 18,
      aliases: [],
      shortName: "sven",
      displayName: "Sven",
      name: "npc_dota_hero_sven",
    },
    {
      id: 19,
      aliases: [],
      shortName: "tiny",
      displayName: "Tiny",
      name: "npc_dota_hero_tiny",
    },
    {
      id: 20,
      aliases: ["vs"],
      shortName: "vengefulspirit",
      displayName: "Vengeful Spirit",
      name: "npc_dota_hero_vengefulspirit",
    },
    {
      id: 21,
      aliases: ["wr"],
      shortName: "windrunner",
      displayName: "Windranger",
      name: "npc_dota_hero_windrunner",
    },
    {
      id: 22,
      aliases: [],
      shortName: "zuus",
      displayName: "Zeus",
      name: "npc_dota_hero_zuus",
    },
    {
      id: 23,
      aliases: [],
      shortName: "kunkka",
      displayName: "Kunkka",
      name: "npc_dota_hero_kunkka",
    },
    {
      id: 25,
      aliases: [],
      shortName: "lina",
      displayName: "Lina",
      name: "npc_dota_hero_lina",
    },
    {
      id: 26,
      aliases: [],
      shortName: "lion",
      displayName: "Lion",
      name: "npc_dota_hero_lion",
    },
    {
      id: 27,
      aliases: ["ss"],
      shortName: "shadow_shaman",
      displayName: "Shadow Shaman",
      name: "npc_dota_hero_shadow_shaman",
    },
    {
      id: 28,
      aliases: [],
      shortName: "slardar",
      displayName: "Slardar",
      name: "npc_dota_hero_slardar",
    },
    {
      id: 29,
      aliases: [],
      shortName: "tidehunter",
      displayName: "Tidehunter",
      name: "npc_dota_hero_tidehunter",
    },
    {
      id: 30,
      aliases: ["wd"],
      shortName: "witch_doctor",
      displayName: "Witch Doctor",
      name: "npc_dota_hero_witch_doctor",
    },
    {
      id: 31,
      aliases: [],
      shortName: "lich",
      displayName: "Lich",
      name: "npc_dota_hero_lich",
    },
    {
      id: 32,
      aliases: [],
      shortName: "riki",
      displayName: "Riki",
      name: "npc_dota_hero_riki",
    },
    {
      id: 33,
      aliases: [],
      shortName: "enigma",
      displayName: "Enigma",
      name: "npc_dota_hero_enigma",
    },
    {
      id: 34,
      aliases: [],
      shortName: "tinker",
      displayName: "Tinker",
      name: "npc_dota_hero_tinker",
    },
    {
      id: 35,
      aliases: [],
      shortName: "sniper",
      displayName: "Sniper",
      name: "npc_dota_hero_sniper",
    },
    {
      id: 36,
      aliases: [],
      shortName: "necrolyte",
      displayName: "Necrophos",
      name: "npc_dota_hero_necrolyte",
    },
    {
      id: 37,
      aliases: [],
      shortName: "warlock",
      displayName: "Warlock",
      name: "npc_dota_hero_warlock",
    },
    {
      id: 38,
      aliases: ["bm"],
      shortName: "beastmaster",
      displayName: "Beastmaster",
      name: "npc_dota_hero_beastmaster",
    },
    {
      id: 39,
      aliases: ["qop"],
      shortName: "queenofpain",
      displayName: "Queen of Pain",
      name: "npc_dota_hero_queenofpain",
    },
    {
      id: 40,
      aliases: [],
      shortName: "venomancer",
      displayName: "Venomancer",
      name: "npc_dota_hero_venomancer",
    },
    {
      id: 41,
      aliases: ["fv"],
      shortName: "faceless_void",
      displayName: "Faceless Void",
      name: "npc_dota_hero_faceless_void",
    },
    {
      id: 42,
      aliases: ["sk", "snk", "wk", "skeleton"],
      shortName: "skeleton_king",
      displayName: "Wraith King",
      name: "npc_dota_hero_skeleton_king",
    },
    {
      id: 43,
      aliases: ["dp"],
      shortName: "death_prophet",
      displayName: "Death Prophet",
      name: "npc_dota_hero_death_prophet",
    },
    {
      id: 44,
      aliases: ["pa", "mortred"],
      shortName: "phantom_assassin",
      displayName: "Phantom Assassin",
      name: "npc_dota_hero_phantom_assassin",
    },
    {
      id: 45,
      aliases: [],
      shortName: "pugna",
      displayName: "Pugna",
      name: "npc_dota_hero_pugna",
    },
    {
      id: 46,
      aliases: ["ta"],
      shortName: "templar_assassin",
      displayName: "Templar Assassin",
      name: "npc_dota_hero_templar_assassin",
    },
    {
      id: 47,
      aliases: [],
      shortName: "viper",
      displayName: "Viper",
      name: "npc_dota_hero_viper",
    },
    {
      id: 48,
      aliases: [],
      shortName: "luna",
      displayName: "Luna",
      name: "npc_dota_hero_luna",
    },
    {
      id: 49,
      aliases: ["dk"],
      shortName: "dragon_knight",
      displayName: "Dragon Knight",
      name: "npc_dota_hero_dragon_knight",
    },
    {
      id: 50,
      aliases: [],
      shortName: "dazzle",
      displayName: "Dazzle",
      name: "npc_dota_hero_dazzle",
    },
    {
      id: 51,
      aliases: [],
      shortName: "rattletrap",
      displayName: "Clockwerk",
      name: "npc_dota_hero_rattletrap",
    },
    {
      id: 52,
      aliases: [],
      shortName: "leshrac",
      displayName: "Leshrac",
      name: "npc_dota_hero_leshrac",
    },
    {
      id: 53,
      aliases: ["np"],
      shortName: "furion",
      displayName: "Nature's Prophet",
      name: "npc_dota_hero_furion",
    },
    {
      id: 54,
      aliases: [],
      shortName: "life_stealer",
      displayName: "Lifestealer",
      name: "npc_dota_hero_life_stealer",
    },
    {
      id: 55,
      aliases: ["ds"],
      shortName: "dark_seer",
      displayName: "Dark Seer",
      name: "npc_dota_hero_dark_seer",
    },
    {
      id: 56,
      aliases: [],
      shortName: "clinkz",
      displayName: "Clinkz",
      name: "npc_dota_hero_clinkz",
    },
    {
      id: 57,
      aliases: [],
      shortName: "omniknight",
      displayName: "Omniknight",
      name: "npc_dota_hero_omniknight",
    },
    {
      id: 58,
      aliases: [],
      shortName: "enchantress",
      displayName: "Enchantress",
      name: "npc_dota_hero_enchantress",
    },
    {
      id: 59,
      aliases: [],
      shortName: "huskar",
      displayName: "Huskar",
      name: "npc_dota_hero_huskar",
    },
    {
      id: 60,
      aliases: ["ns"],
      shortName: "night_stalker",
      displayName: "Night Stalker",
      name: "npc_dota_hero_night_stalker",
    },
    {
      id: 61,
      aliases: ["bm"],
      shortName: "broodmother",
      displayName: "Broodmother",
      name: "npc_dota_hero_broodmother",
    },
    {
      id: 62,
      aliases: ["bh"],
      shortName: "bounty_hunter",
      displayName: "Bounty Hunter",
      name: "npc_dota_hero_bounty_hunter",
    },
    {
      id: 63,
      aliases: [],
      shortName: "weaver",
      displayName: "Weaver",
      name: "npc_dota_hero_weaver",
    },
    {
      id: 64,
      aliases: [],
      shortName: "jakiro",
      displayName: "Jakiro",
      name: "npc_dota_hero_jakiro",
    },
    {
      id: 65,
      aliases: ["br"],
      shortName: "batrider",
      displayName: "Batrider",
      name: "npc_dota_hero_batrider",
    },
    {
      id: 66,
      aliases: [],
      shortName: "chen",
      displayName: "Chen",
      name: "npc_dota_hero_chen",
    },
    {
      id: 67,
      aliases: [],
      shortName: "spectre",
      displayName: "Spectre",
      name: "npc_dota_hero_spectre",
    },
    {
      id: 68,
      aliases: ["aa"],
      shortName: "ancient_apparition",
      displayName: "Ancient Apparition",
      name: "npc_dota_hero_ancient_apparition",
    },
    {
      id: 69,
      aliases: ["db"],
      shortName: "doom_bringer",
      displayName: "Doom",
      name: "npc_dota_hero_doom_bringer",
    },
    {
      id: 70,
      aliases: [],
      shortName: "ursa",
      displayName: "Ursa",
      name: "npc_dota_hero_ursa",
    },
    {
      id: 71,
      aliases: ["sb"],
      shortName: "spirit_breaker",
      displayName: "Spirit Breaker",
      name: "npc_dota_hero_spirit_breaker",
    },
    {
      id: 72,
      aliases: [],
      shortName: "gyrocopter",
      displayName: "Gyrocopter",
      name: "npc_dota_hero_gyrocopter",
    },
    {
      id: 73,
      aliases: [],
      shortName: "alchemist",
      displayName: "Alchemist",
      name: "npc_dota_hero_alchemist",
    },
    {
      id: 74,
      aliases: [],
      shortName: "invoker",
      displayName: "Invoker",
      name: "npc_dota_hero_invoker",
    },
    {
      id: 75,
      aliases: [],
      shortName: "silencer",
      displayName: "Silencer",
      name: "npc_dota_hero_silencer",
    },
    {
      id: 76,
      aliases: ["od"],
      shortName: "obsidian_destroyer",
      displayName: "Outworld Devourer",
      name: "npc_dota_hero_obsidian_destroyer",
    },
    {
      id: 77,
      aliases: [],
      shortName: "lycan",
      displayName: "Lycan",
      name: "npc_dota_hero_lycan",
    },
    {
      id: 78,
      aliases: ["bm"],
      shortName: "brewmaster",
      displayName: "Brewmaster",
      name: "npc_dota_hero_brewmaster",
    },
    {
      id: 79,
      aliases: ["sd"],
      shortName: "shadow_demon",
      displayName: "Shadow Demon",
      name: "npc_dota_hero_shadow_demon",
    },
    {
      id: 80,
      aliases: ["ld"],
      shortName: "lone_druid",
      displayName: "Lone Druid",
      name: "npc_dota_hero_lone_druid",
    },
    {
      id: 81,
      aliases: ["ck"],
      shortName: "chaos_knight",
      displayName: "Chaos Knight",
      name: "npc_dota_hero_chaos_knight",
    },
    {
      id: 82,
      aliases: ["geomancer", "meepwn"],
      shortName: "meepo",
      displayName: "Meepo",
      name: "npc_dota_hero_meepo",
    },
    {
      id: 83,
      aliases: [],
      shortName: "treant",
      displayName: "Treant Protector",
      name: "npc_dota_hero_treant",
    },
    {
      id: 84,
      aliases: ["om"],
      shortName: "ogre_magi",
      displayName: "Ogre Magi",
      name: "npc_dota_hero_ogre_magi",
    },
    {
      id: 85,
      aliases: ["dirge"],
      shortName: "undying",
      displayName: "Undying",
      name: "npc_dota_hero_undying",
    },
    {
      id: 86,
      aliases: ["rubick"],
      shortName: "rubick",
      displayName: "Rubick",
      name: "npc_dota_hero_rubick",
    },
    {
      id: 87,
      aliases: ["disruptor"],
      shortName: "disruptor",
      displayName: "Disruptor",
      name: "npc_dota_hero_disruptor",
    },
    {
      id: 88,
      aliases: ["na"],
      shortName: "nyx_assassin",
      displayName: "Nyx Assassin",
      name: "npc_dota_hero_nyx_assassin",
    },
    {
      id: 89,
      aliases: ["naga"],
      shortName: "naga_siren",
      displayName: "Naga Siren",
      name: "npc_dota_hero_naga_siren",
    },
    {
      id: 90,
      aliases: ["keeper", "ezalor", "kotl"],
      shortName: "keeper_of_the_light",
      displayName: "Keeper of the Light",
      name: "npc_dota_hero_keeper_of_the_light",
    },
    {
      id: 91,
      aliases: ["wisp"],
      shortName: "wisp",
      displayName: "Io",
      name: "npc_dota_hero_wisp",
    },
    {
      id: 92,
      aliases: ["visage"],
      shortName: "visage",
      displayName: "Visage",
      name: "npc_dota_hero_visage",
    },
    {
      id: 93,
      aliases: ["slark"],
      shortName: "slark",
      displayName: "Slark",
      name: "npc_dota_hero_slark",
    },
    {
      id: 94,
      aliases: ["medusa,gorgon"],
      shortName: "medusa",
      displayName: "Medusa",
      name: "npc_dota_hero_medusa",
    },
    {
      id: 95,
      aliases: ["troll,jahrakal"],
      shortName: "troll_warlord",
      displayName: "Troll Warlord",
      name: "npc_dota_hero_troll_warlord",
    },
    {
      id: 96,
      aliases: ["centaur"],
      shortName: "centaur",
      displayName: "Centaur Warrunner",
      name: "npc_dota_hero_centaur",
    },
    {
      id: 97,
      aliases: ["magnataur, magnus"],
      shortName: "magnataur",
      displayName: "Magnus",
      name: "npc_dota_hero_magnataur",
    },
    {
      id: 98,
      aliases: ["Rizzrack", " Shredder", " Timbersaw"],
      shortName: "shredder",
      displayName: "Timbersaw",
      name: "npc_dota_hero_shredder",
    },
    {
      id: 99,
      aliases: ["Rigwarl", "bb"],
      shortName: "bristleback",
      displayName: "Bristleback",
      name: "npc_dota_hero_bristleback",
    },
    {
      id: 100,
      aliases: ["Tuskarr"],
      shortName: "tusk",
      displayName: "Tusk",
      name: "npc_dota_hero_tusk",
    },
    {
      id: 101,
      aliases: ["dragonus"],
      shortName: "skywrath_mage",
      displayName: "Skywrath Mage",
      name: "npc_dota_hero_skywrath_mage",
    },
    {
      id: 102,
      aliases: ["Abaddon"],
      shortName: "abaddon",
      displayName: "Abaddon",
      name: "npc_dota_hero_abaddon",
    },
    {
      id: 103,
      aliases: ["TC,Cairne"],
      shortName: "elder_titan",
      displayName: "Elder Titan",
      name: "npc_dota_hero_elder_titan",
    },
    {
      id: 104,
      aliases: ["Tresdin,Legion"],
      shortName: "legion_commander",
      displayName: "Legion Commander",
      name: "npc_dota_hero_legion_commander",
    },
    {
      id: 105,
      aliases: [],
      shortName: "techies",
      displayName: "Techies",
      name: "npc_dota_hero_techies",
    },
    {
      id: 106,
      aliases: ["Xin,Ember"],
      shortName: "ember_spirit",
      displayName: "Ember Spirit",
      name: "npc_dota_hero_ember_spirit",
    },
    {
      id: 107,
      aliases: ["Kaolin,Earth"],
      shortName: "earth_spirit",
      displayName: "Earth Spirit",
      name: "npc_dota_hero_earth_spirit",
    },
    {
      id: 108,
      aliases: ["PitLord,Azgalor"],
      shortName: "abyssal_underlord",
      displayName: "Underlord",
      name: "npc_dota_hero_abyssal_underlord",
    },
    {
      id: 109,
      aliases: ["tb"],
      shortName: "terrorblade",
      displayName: "Terrorblade",
      name: "npc_dota_hero_terrorblade",
    },
    {
      id: 110,
      aliases: ["ph"],
      shortName: "phoenix",
      displayName: "Phoenix",
      name: "npc_dota_hero_phoenix",
    },
    {
      id: 111,
      aliases: ["ora"],
      shortName: "oracle",
      displayName: "Oracle",
      name: "npc_dota_hero_oracle",
    },
    {
      id: 112,
      aliases: [],
      shortName: "winter_wyvern",
      displayName: "Winter Wyvern",
      name: "npc_dota_hero_winter_wyvern",
    },
    {
      id: 113,
      aliases: ["zet"],
      shortName: "arc_warden",
      displayName: "Arc Warden",
      name: "npc_dota_hero_arc_warden",
    },
    {
      id: 114,
      aliases: ["mk"],
      shortName: "monkey_king",
      displayName: "Monkey King",
      name: "npc_dota_hero_monkey_king",
    },
    {
      id: 119,
      aliases: [],
      shortName: "dark_willow",
      displayName: "Dark Willow",
      name: "npc_dota_hero_dark_willow",
    },
    {
      id: 120,
      aliases: ["ar"],
      shortName: "pangolier",
      displayName: "Pangolier",
      name: "npc_dota_hero_pangolier",
    },
    {
      id: 121,
      aliases: ["gs"],
      shortName: "grimstroke",
      displayName: "Grimstroke",
      name: "npc_dota_hero_grimstroke",
    },
    {
      id: 126,
      aliases: ["Void,VS,Inai"],
      shortName: "void_spirit",
      displayName: "Void Spirit",
      name: "npc_dota_hero_void_spirit",
    },
    {
      id: 128,
      aliases: ["snap,mortimer"],
      shortName: "snapfire",
      displayName: "Snapfire",
      name: "npc_dota_hero_snapfire",
    },
    {
      id: 129,
      aliases: ["mars"],
      shortName: "mars",
      displayName: "Mars",
      name: "npc_dota_hero_mars",
    },
  ],
};
